//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business.CL_WS_ReceptionService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://reception.com/", ConfigurationName="CL_WS_ReceptionService.IWSReception")]
    public interface IWSReception {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reception.com/IWSReception/MessageRequest", ReplyAction="http://reception.com/IWSReception/MessageResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string Message(string texte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reception.com/IWSReception/MessageRequest", ReplyAction="http://reception.com/IWSReception/MessageResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> MessageAsync(string texte);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reception.com/IWSReception/MessageJMSRequest", ReplyAction="http://reception.com/IWSReception/MessageJMSResponse")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string MessageJMS(string nom, byte[] message, string cle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://reception.com/IWSReception/MessageJMSRequest", ReplyAction="http://reception.com/IWSReception/MessageJMSResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> MessageJMSAsync(string nom, byte[] message, string cle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSReceptionChannel : Business.CL_WS_ReceptionService.IWSReception, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSReceptionClient : System.ServiceModel.ClientBase<Business.CL_WS_ReceptionService.IWSReception>, Business.CL_WS_ReceptionService.IWSReception {
        
        public WSReceptionClient() {
        }
        
        public WSReceptionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSReceptionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSReceptionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSReceptionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Message(string texte) {
            return base.Channel.Message(texte);
        }
        
        public System.Threading.Tasks.Task<string> MessageAsync(string texte) {
            return base.Channel.MessageAsync(texte);
        }
        
        public string MessageJMS(string nom, byte[] message, string cle) {
            return base.Channel.MessageJMS(nom, message, cle);
        }
        
        public System.Threading.Tasks.Task<string> MessageJMSAsync(string nom, byte[] message, string cle) {
            return base.Channel.MessageJMSAsync(nom, message, cle);
        }
    }
}
