//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34014
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEN_client.CL_SERVC {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="STG", Namespace="http://schemas.datacontract.org/2004/07/Dad_server_component.Server_component", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GEN_client.CL_SERVC.FILE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[][]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    public partial class STG : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[][] dataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string infoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statut_opField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenApllField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tokenUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int userIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[][] data {
            get {
                return this.dataField;
            }
            set {
                if ((object.ReferenceEquals(this.dataField, value) != true)) {
                    this.dataField = value;
                    this.RaisePropertyChanged("data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string info {
            get {
                return this.infoField;
            }
            set {
                if ((object.ReferenceEquals(this.infoField, value) != true)) {
                    this.infoField = value;
                    this.RaisePropertyChanged("info");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operationName {
            get {
                return this.operationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.operationNameField, value) != true)) {
                    this.operationNameField = value;
                    this.RaisePropertyChanged("operationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool statut_op {
            get {
                return this.statut_opField;
            }
            set {
                if ((this.statut_opField.Equals(value) != true)) {
                    this.statut_opField = value;
                    this.RaisePropertyChanged("statut_op");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tokenApll {
            get {
                return this.tokenApllField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenApllField, value) != true)) {
                    this.tokenApllField = value;
                    this.RaisePropertyChanged("tokenApll");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tokenUser {
            get {
                return this.tokenUserField;
            }
            set {
                if ((object.ReferenceEquals(this.tokenUserField, value) != true)) {
                    this.tokenUserField = value;
                    this.RaisePropertyChanged("tokenUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int userId {
            get {
                return this.userIdField;
            }
            set {
                if ((this.userIdField.Equals(value) != true)) {
                    this.userIdField = value;
                    this.RaisePropertyChanged("userId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FILE", Namespace="http://schemas.datacontract.org/2004/07/Dad_server_component.Server_component", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class FILE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime file_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string file_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string content {
            get {
                return this.contentField;
            }
            set {
                if ((object.ReferenceEquals(this.contentField, value) != true)) {
                    this.contentField = value;
                    this.RaisePropertyChanged("content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_code {
            get {
                return this.file_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.file_codeField, value) != true)) {
                    this.file_codeField = value;
                    this.RaisePropertyChanged("file_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime file_date {
            get {
                return this.file_dateField;
            }
            set {
                if ((this.file_dateField.Equals(value) != true)) {
                    this.file_dateField = value;
                    this.RaisePropertyChanged("file_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_email {
            get {
                return this.file_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.file_emailField, value) != true)) {
                    this.file_emailField = value;
                    this.RaisePropertyChanged("file_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_name {
            get {
                return this.file_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.file_nameField, value) != true)) {
                    this.file_nameField = value;
                    this.RaisePropertyChanged("file_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string file_url {
            get {
                return this.file_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.file_urlField, value) != true)) {
                    this.file_urlField = value;
                    this.RaisePropertyChanged("file_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int state {
            get {
                return this.stateField;
            }
            set {
                if ((this.stateField.Equals(value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CL_SERVC.I_SERVC")]
    public interface I_SERVC {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_SERVC/m_service", ReplyAction="http://tempuri.org/I_SERVC/m_serviceResponse")]
        GEN_client.CL_SERVC.STG m_service(GEN_client.CL_SERVC.STG msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_SERVC/m_service", ReplyAction="http://tempuri.org/I_SERVC/m_serviceResponse")]
        System.Threading.Tasks.Task<GEN_client.CL_SERVC.STG> m_serviceAsync(GEN_client.CL_SERVC.STG msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_SERVC/file", ReplyAction="http://tempuri.org/I_SERVC/fileResponse")]
        void file([System.ServiceModel.MessageParameterAttribute(Name="file")] GEN_client.CL_SERVC.FILE file1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/I_SERVC/file", ReplyAction="http://tempuri.org/I_SERVC/fileResponse")]
        System.Threading.Tasks.Task fileAsync(GEN_client.CL_SERVC.FILE file);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface I_SERVCChannel : GEN_client.CL_SERVC.I_SERVC, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class I_SERVCClient : System.ServiceModel.ClientBase<GEN_client.CL_SERVC.I_SERVC>, GEN_client.CL_SERVC.I_SERVC {
        
        public I_SERVCClient() {
        }
        
        public I_SERVCClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public I_SERVCClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_SERVCClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public I_SERVCClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GEN_client.CL_SERVC.STG m_service(GEN_client.CL_SERVC.STG msg) {
            return base.Channel.m_service(msg);
        }
        
        public System.Threading.Tasks.Task<GEN_client.CL_SERVC.STG> m_serviceAsync(GEN_client.CL_SERVC.STG msg) {
            return base.Channel.m_serviceAsync(msg);
        }
        
        public void file(GEN_client.CL_SERVC.FILE file1) {
            base.Channel.file(file1);
        }
        
        public System.Threading.Tasks.Task fileAsync(GEN_client.CL_SERVC.FILE file) {
            return base.Channel.fileAsync(file);
        }
    }
}
